# global configuration for all the fingerprinting methods
fingerprint_method: 'mdir'
cached_fingerprints_path: 'cache/mdir/mdir_fingerprints.pth'
re_fingerprinting: False
fingerprint_type: 'white-box'
seed: 42

# configuration for pdf